package com.example.slavinntube.entity;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.*;
import java.util.Date;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "user")
@Transactional
public class User {

    // User UUID generated by Hibernate
    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(
            name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator"
    )
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // Current time non updatable
    @Temporal(value = TemporalType.TIMESTAMP)
    @Column(name= "createdAt", updatable=false)
    @CreationTimestamp
    private Date createdAt;

    @Column(name = "username")
    private String username;

    @Column(name = "email")
    private String email;


    // Profile picture of user
    @Column(name = "avatar")
    private String avatar;

    // Cover art url for a users profile page
    @Column(name = "cover")
    private String  cover;


    /// List of all videos a user has uploaded
    @OneToMany
    @Column(name = "videos")
    private List<Video> videos;

    // List of all liked videos by a user
    @OneToMany
    @JoinColumn(name = "userId")
    private List<VideoLike> videoLikes;

    // List of all users follower current user
    @OneToMany
    @JoinColumn(name ="subscriber")
    private List<Subscription> subscribers;


//     List of all users current user follows
    @OneToMany
    @Column(name = "subscribed")
    private  List<Subscription> subscribed;

    public User() {
    }

    public User(String username, String email) {
//        this.id = UUID.randomUUID();
//        this.createdAt = new Date();
        this.username = username;
        this.email = email;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    public List<Video> getVideos() {
        return videos;
    }

    public void setVideos(List<Video> videos) {
        this.videos = videos;
    }

    public List<VideoLike> getVideoLikes() {
        return videoLikes;
    }

    public void setVideoLikes(List<VideoLike> videoLikes) {
        this.videoLikes = videoLikes;
    }

    public List<Subscription> getSubscribers() {
        return subscribers;
    }

    public void setSubscribers(List<Subscription> subscribers) {
        this.subscribers = subscribers;
    }

    public List<Subscription> getSubscribed() {
        return subscribed;
    }

    public void setSubscribed(List<Subscription> subscribed) {
        this.subscribed = subscribed;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", createdAt=" + createdAt +
                ", username='" + username + '\'' +
                ", email='" + email + '\'' +
                ", avatar=" + avatar +
                ", cover=" + cover +
                ", videos=" + videos +
                ", subscribers=" + subscribers +
                ", subscribedTo=" + subscribed +
                '}';
    }
}
